services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_healthcare
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: HealthcareDB
      MYSQL_USER: healthcare_user
      MYSQL_PASSWORD: healthcare_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - healthcare_network
    command: --default-authentication-plugin=caching_sha2_password

  postgres_db:
    image: postgres:15
    container_name: postgres_healthcare
    environment:
      POSTGRES_DB: HealthcareDB
      POSTGRES_USER: healthcare_user
      POSTGRES_PASSWORD: healthcare_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare_network

  doctors_service:
    build: .
    container_name: doctors_service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DATABASE_URL=mysql://healthcare_user:healthcare_password@mysql_db:3306/HealthcareDB
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
    networks:
      - healthcare_network
    depends_on:
      - mysql_db

  patients_service:
    build: .
    container_name: patients_service
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DATABASE_URL=mysql://healthcare_user:healthcare_password@mysql_db:3306/HealthcareDB
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
    networks:
      - healthcare_network
    depends_on:
      - mysql_db

  appointments_service:
    build: .
    container_name: appointments_service
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DATABASE_URL=postgresql://healthcare_user:healthcare_password@postgres_db:5432/HealthcareDB
    networks:
      - healthcare_network
    depends_on:
      - postgres_db

  ai_chatbot_service:
    build: .
    container_name: ai_chatbot_service
    command: python manage.py runserver 0.0.0.0:8003
    ports:
      - "8003:8003"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DATABASE_URL=postgresql://healthcare_user:healthcare_password@postgres_db:5432/HealthcareDB
    networks:
      - healthcare_network
    depends_on:
      - postgres_db

volumes:
  mysql_data:
  postgres_data:
  static_volume:

networks:
  healthcare_network:
    driver: bridge
